export default {
  GET_NEWS_START: 'info/GET_NEWS_START',
  GET_NEWS_SUCCESS: 'info/GET_NEWS_SUCCESS',
  GET_NEWS_ERROR: 'info/GET_NEWS_ERROR',

  GET_WEATHER_START: 'info/GET_WEATHER_START',
  GET_WEATHER_SUCCESS: 'info/GET_WEATHER_SUCCESS',
  GET_WEATHER_ERROR: 'info/GET_WEATHER_ERROR',

  LOGIN: 'info/LOGIN',
  LOGOUT: 'info/LOGOUT',
  DELETE_WEATHER: 'info/DELETE_WEATHER',
  ADD_NEWS: 'info/ADD_NEWS',
  DELETE_PROFILE: 'info/DELETE_PROFILE'
};
